from dateutil import tz


# DAYS
MON = 1
TUE = 2
WED = 3
THU = 4
FRI = 5
SAT = 6
SUN = 0

# STOPS
MPALTATZI_PROS = "041"
MPALTATZI_APO = "005"
DIMOTIKI_PROS = "001"
TSALDARI_PROS = "097"
KONEL_PROS = "134"
KONEL_APO = "143"
TEXN_APO = "004"
ESTIES_PROS = "139"
HMMY_PROS = "136"
HMMY_APO = "142"
LEOF_STRATOU_PROS = "096"
LEOF_STRATOU_APO = "117"
POL_PROS = "200"
POL_APO = "135"
ARCH_PROS = "137"
ARCH_APO = "141"
ENV_PROS = "138"
ENV_APO = "140"
ELENA_APO = "114"
PROKAT = "203"

# OTHER
PAGE_URL = "https://xanthi.citybus.gr/el/stops"
API_URL = "https://sarkastika-xanthis.fly.dev"
#API_URL = "http://localhost:8000"
ROUTE = "07"
REFRESH_HOURS = 4
TZ = tz.gettz('Europe / Berlin')

# 07 PATH
LINE_PATH = [
	DIMOTIKI_PROS,
	MPALTATZI_PROS,
	LEOF_STRATOU_PROS,
	TSALDARI_PROS,
	KONEL_PROS,
	POL_PROS,
	HMMY_PROS,
	ARCH_PROS,
	ENV_PROS,
	ESTIES_PROS,
	ENV_APO,
	ARCH_APO,
	HMMY_APO,
	POL_APO,
	KONEL_APO,
	ELENA_APO,
	LEOF_STRATOU_APO,
	TEXN_APO,
	MPALTATZI_APO,
]